# Dataset Project

**Author:** Santosh Ganesan

**Date:** 15 October 2024

## Running this notebook

TODO: add instructions for running this notebook

## Introduction


## Dataset Project Proposal

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib import rc

from math import pi
#from palettable.colorbrewer.qualitative import Pastel1_7

# Suppress specific warnings from pandas
pd.options.mode.chained_assignment = None

# Suppress warnings in general (use with caution)
import warnings
warnings.filterwarnings('ignore')

In [18]:

df = pd.read_excel('shelter-report-data-export-august-2024.xlsx')

#df.head(5)
df = df.drop(columns=['Unnamed: 10'])

df.info()

#Project the number of rows and columns
#print(df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7310 entries, 0 to 7309
Data columns (total 35 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   1 non-null      object
 1   Unnamed: 1   7308 non-null   object
 2   Unnamed: 2   7308 non-null   object
 3   Unnamed: 3   7308 non-null   object
 4   Unnamed: 4   7308 non-null   object
 5   Unnamed: 5   7308 non-null   object
 6   Unnamed: 6   7308 non-null   object
 7   Unnamed: 7   7308 non-null   object
 8   Unnamed: 8   7308 non-null   object
 9   Unnamed: 9   7308 non-null   object
 10  Unnamed: 11  0 non-null      float64
 11  Unnamed: 12  7308 non-null   object
 12  Unnamed: 13  7308 non-null   object
 13  Unnamed: 14  7308 non-null   object
 14  Unnamed: 15  7308 non-null   object
 15  Unnamed: 16  7308 non-null   object
 16  Unnamed: 17  7308 non-null   object
 17  Unnamed: 18  7308 non-null   object
 18  Unnamed: 19  7308 non-null   object
 19  Unnamed: 20  7308 non-null   object
 20  Unnamed: 21  7308 non-null   object
 21  Unnamed: 22  7308 non-null   object
 22  Unnamed: 23  7308 non-null   object
 23  Unnamed: 24  7308 non-null   object
 24  Unnamed: 25  7308 non-null   object
 25  Unnamed: 26  7308 non-null   object
 26  Unnamed: 27  7308 non-null   object
 27  Unnamed: 28  7308 non-null   object
 28  Unnamed: 29  7308 non-null   object
 29  Unnamed: 30  7308 non-null   object
 30  Unnamed: 31  7308 non-null   object
 31  Unnamed: 32  7308 non-null   object
 32  Unnamed: 33  7308 non-null   object
 33  Unnamed: 34  7308 non-null   object
 34  Unnamed: 35  7308 non-null   object
dtypes: float64(1), object(34)
memory usage: 2.0+ MB

# Cleaning the data

In [19]:
# Assuming df is already loaded
headers = df.iloc[0]
df = pd.DataFrame(df.values[1:], columns=headers)

# Reset the index
df.reset_index(drop=True, inplace=True)

# Display the DataFrame
df

,Georgia Department of Agriculture: Shelter Report Data Export,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Report Period Start,Report Period End,License Number,Shelter Name,Canine starting animal count,Feline starting animal count,Canine stray at large,Feline stray at large,Canine relinquished by owner,NaN,Canine intake owner intended euthanasia,Feline intake owner intended euthanasia,Canine transferred in from agency,Feline transferred in from agency,Canine other intakes,Feline other intakes,Canine adoption,Feline adoption,Canine returned to owner,Feline returned to owner,Canine transferred to another agency,Feline transferred to another agency,Canine returned to field,Feline returned to field,Canine other live outcome,Feline other live outcome,Canine died in care,Feline died in care,Canine lost in care,Feline list in care,Canine shelter euthanasia,Feline shelter euthanasia,Canine owner intended euthanasia,Feline owner intended euthanasia
2,NaN,2020-07-01 00:00:00,2020-07-31 00:00:00,33105331,ALAPAHA ANIMAL CONTROL/SHELTER,0,0,12,3,3,NaN,0,0,0,0,0,0,2,0,1,0,12,2,0,0,0,0,0,0,0,1,0,0,0,0
3,NaN,2020-08-01 00:00:00,2020-08-31 00:00:00,33105331,ALAPAHA ANIMAL CONTROL/SHELTER,27,11,18,11,9,NaN,0,0,0,0,0,0,0,0,2,0,24,11,0,0,0,0,0,0,0,0,0,0,0,0
4,NaN,2020-09-01 00:00:00,2020-09-30 00:00:00,33105331,ALAPAHA ANIMAL CONTROL/SHELTER,2,10,2,10,0,NaN,0,0,0,0,0,0,0,0,0,0,2,10,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7304,NaN,2024-04-01 00:00:00,2024-04-30 00:00:00,3396397,WORTH COUNTY ANIMAL SHELTER,36,5,37,41,32,NaN,0,0,21,64,0,0,27,22,18,0,26,35,0,0,0,127,0,0,0,0,22,0,0,0
7305,NaN,2024-05-01 00:00:00,2024-05-31 00:00:00,3396397,WORTH COUNTY ANIMAL SHELTER,19,17,52,47,14,NaN,0,0,10,31,0,0,6,17,36,2,31,24,0,0,0,39,0,0,0,0,17,0,0,0
7306,NaN,2024-06-01 00:00:00,2024-06-30 00:00:00,3396397,WORTH COUNTY ANIMAL SHELTER,38,40,53,87,13,NaN,0,0,6,17,0,0,8,7,15,0,23,15,0,0,0,60,0,0,0,0,12,2,0,0
7307,NaN,2024-07-01 00:00:00,2024-07-31 00:00:00,3396397,WORTH COUNTY ANIMAL SHELTER,61,35,66,51,9,NaN,0,0,22,16,0,0,6,2,26,1,21,22,0,0,0,46,0,0,0,0,21,0,0,0
7308,NaN,2024-08-01 00:00:00,2024-08-31 00:00:00,3396397,WORTH COUNTY ANIMAL SHELTER,52,30,67,43,8,NaN,0,0,12,8,0,0,6,5,7,2,61,33,0,0,0,45,0,0,0,0,16,2,0,0

In [20]:
# Create a new DataFrame starting from the 2nd row
new_df = df.iloc[1:]

# Reset the index of the new DataFrame
new_df = new_df.reset_index(drop=True)

# Dispolay the dataframe
new_df

,Georgia Department of Agriculture: Shelter Report Data Export,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,Report Period Start,Report Period End,License Number,Shelter Name,Canine starting animal count,Feline starting animal count,Canine stray at large,Feline stray at large,Canine relinquished by owner,NaN,Canine intake owner intended euthanasia,Feline intake owner intended euthanasia,Canine transferred in from agency,Feline transferred in from agency,Canine other intakes,Feline other intakes,Canine adoption,Feline adoption,Canine returned to owner,Feline returned to owner,Canine transferred to another agency,Feline transferred to another agency,Canine returned to field,Feline returned to field,Canine other live outcome,Feline other live outcome,Canine died in care,Feline died in care,Canine lost in care,Feline list in care,Canine shelter euthanasia,Feline shelter euthanasia,Canine owner intended euthanasia,Feline owner intended euthanasia
1,NaN,2020-07-01 00:00:00,2020-07-31 00:00:00,33105331,ALAPAHA ANIMAL CONTROL/SHELTER,0,0,12,3,3,NaN,0,0,0,0,0,0,2,0,1,0,12,2,0,0,0,0,0,0,0,1,0,0,0,0
2,NaN,2020-08-01 00:00:00,2020-08-31 00:00:00,33105331,ALAPAHA ANIMAL CONTROL/SHELTER,27,11,18,11,9,NaN,0,0,0,0,0,0,0,0,2,0,24,11,0,0,0,0,0,0,0,0,0,0,0,0
3,NaN,2020-09-01 00:00:00,2020-09-30 00:00:00,33105331,ALAPAHA ANIMAL CONTROL/SHELTER,2,10,2,10,0,NaN,0,0,0,0,0,0,0,0,0,0,2,10,0,0,0,0,0,0,0,0,0,0,0,0
4,NaN,2020-10-01 00:00:00,2020-10-31 00:00:00,33105331,ALAPAHA ANIMAL CONTROL/SHELTER,11,0,11,0,0,NaN,0,0,0,0,0,0,0,0,2,0,9,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7303,NaN,2024-04-01 00:00:00,2024-04-30 00:00:00,3396397,WORTH COUNTY ANIMAL SHELTER,36,5,37,41,32,NaN,0,0,21,64,0,0,27,22,18,0,26,35,0,0,0,127,0,0,0,0,22,0,0,0
7304,NaN,2024-05-01 00:00:00,2024-05-31 00:00:00,3396397,WORTH COUNTY ANIMAL SHELTER,19,17,52,47,14,NaN,0,0,10,31,0,0,6,17,36,2,31,24,0,0,0,39,0,0,0,0,17,0,0,0
7305,NaN,2024-06-01 00:00:00,2024-06-30 00:00:00,3396397,WORTH COUNTY ANIMAL SHELTER,38,40,53,87,13,NaN,0,0,6,17,0,0,8,7,15,0,23,15,0,0,0,60,0,0,0,0,12,2,0,0
7306,NaN,2024-07-01 00:00:00,2024-07-31 00:00:00,3396397,WORTH COUNTY ANIMAL SHELTER,61,35,66,51,9,NaN,0,0,22,16,0,0,6,2,26,1,21,22,0,0,0,46,0,0,0,0,21,0,0,0
7307,NaN,2024-08-01 00:00:00,2024-08-31 00:00:00,3396397,WORTH COUNTY ANIMAL SHELTER,52,30,67,43,8,NaN,0,0,12,8,0,0,6,5,7,2,61,33,0,0,0,45,0,0,0,0,16,2,0,0

In [14]:
pd.set_option('display.max_columns', None)
df.info

<bound method DataFrame.info of 0    Georgia Department of Agriculture: Shelter Report Data Export  \
0                                                   NaN
1                                                   NaN
2                                                   NaN
3                                                   NaN
4                                                   NaN
...                                                 ...
7304                                                NaN
7305                                                NaN
7306                                                NaN
7307                                                NaN
7308                                                NaN

0                     NaN                  NaN             NaN  \
0                     NaN                  NaN             NaN
1     Report Period Start    Report Period End  License Number
2     2020-07-01 00:00:00  2020-07-31 00:00:00        33105331
3     2020-08-01 00:00:00  2020-08-31 00:00:00        33105331
4     2020-09-01 00:00:00  2020-09-30 00:00:00        33105331
...                   ...                  ...             ...
7304  2024-04-01 00:00:00  2024-04-30 00:00:00         3396397
7305  2024-05-01 00:00:00  2024-05-31 00:00:00         3396397
7306  2024-06-01 00:00:00  2024-06-30 00:00:00         3396397
7307  2024-07-01 00:00:00  2024-07-31 00:00:00         3396397
7308  2024-08-01 00:00:00  2024-08-31 00:00:00         3396397

0                                NaN                           NaN  \
0                                NaN                           NaN
1                       Shelter Name  Canine starting animal count
2     ALAPAHA ANIMAL CONTROL/SHELTER                             0
3     ALAPAHA ANIMAL CONTROL/SHELTER                            27
4     ALAPAHA ANIMAL CONTROL/SHELTER                             2
...                              ...                           ...
7304     WORTH COUNTY ANIMAL SHELTER                            36
7305     WORTH COUNTY ANIMAL SHELTER                            19
7306     WORTH COUNTY ANIMAL SHELTER                            38
7307     WORTH COUNTY ANIMAL SHELTER                            61
7308     WORTH COUNTY ANIMAL SHELTER                            52

0                              NaN                    NaN  \
0                              NaN                    NaN
1     Feline starting animal count  Canine stray at large
2                                0                     12
3                               11                     18
4                               10                      2
...                            ...                    ...
7304                             5                     37
7305                            17                     52
7306                            40                     53
7307                            35                     66
7308                            30                     67

0                       NaN                           NaN  NaN  \
0                       NaN                           NaN  NaN
1     Feline stray at large  Canine relinquished by owner  NaN
2                         3                             3  NaN
3                        11                             9  NaN
4                        10                             0  NaN
...                     ...                           ...  ...
7304                     41                            32  NaN
7305                     47                            14  NaN
7306                     87                            13  NaN
7307                     51                             9  NaN
7308                     43                             8  NaN

0                                         NaN  \
0                                         NaN
1     Canine intake owner intended euthanasia
2                                           0
3                                           0
4                                           0
...                                       ...
7304                                        0
7305                                        0
7306                                        0
7307                                        0
7308                                        0

0                                         NaN  \
0                                         NaN
1     Feline intake owner intended euthanasia
2                                           0
3                                           0
4                                           0
...                                       ...
7304                                        0
7305                                        0
7306                                        0
7307                                        0
7308                                        0

0                                   NaN                                NaN  \
0                                   NaN                                NaN
1     Canine transferred in from agency  Feline transferred in from agency
2                                     0                                  0
3                                     0                                  0
4                                     0                                  0
...                                 ...                                ...
7304                                 21                                 64
7305                                 10                                 31
7306                                  6                                 17
7307                                 22                                 16
7308                                 12                                  8

0                      NaN                   NaN              NaN  \
0                      NaN                   NaN              NaN
1     Canine other intakes  Feline other intakes  Canine adoption
2                        0                     0                2
3                        0                     0                0
4                        0                     0                0
...                    ...                   ...              ...
7304                     0                     0               27
7305                     0                     0                6
7306                     0                     0                8
7307                     0                     0                6
7308                     0                     0                6

0                 NaN                       NaN                       NaN  \
0                 NaN                       NaN                       NaN
1     Feline adoption  Canine returned to owner  Feline returned to owner
2                   0                         1                         0
3                   0                         2                         0
4                   0                         0                         0
...               ...                       ...                       ...
7304               22                        18                         0
7305               17                        36                         2
7306                7                        15                         0
7307                2                        26                         1
7308                5                         7                         2

0                                      NaN  \
0                                      NaN
1     Canine transferred to another agency
2                                       12
3                                       24
4                                        2
...                                    ...
7304                                    26
7305                                    31
7306                                    23
7307                                    21
7308                                    61

0                                      NaN                       NaN  \
0                                      NaN                       NaN
1     Feline transferred to another agency  Canine returned to field
2                                        2                         0
3                                       11                         0
4                                       10                         0
...                                    ...                       ...
7304                                    35                         0
7305                                    24                         0
7306                                    15                         0
7307                                    22                         0
7308                                    33                         0

0                          NaN                        NaN  \
0                          NaN                        NaN
1     Feline returned to field  Canine other live outcome
2                            0                          0
3                            0                          0
4                            0                          0
...                        ...                        ...
7304                         0                          0
7305                         0                          0
7306                         0                          0
7307                         0                          0
7308                         0                          0

0                           NaN                  NaN                  NaN  \
0                           NaN                  NaN                  NaN
1     Feline other live outcome  Canine died in care  Feline died in care
2                             0                    0                    0
3                             0                    0                    0
4                             0                    0                    0
...                         ...                  ...                  ...
7304                        127                    0                    0
7305                         39                    0                    0
7306                         60                    0                    0
7307                         46                    0                    0
7308                         45                    0                    0

0                     NaN                  NaN                        NaN  \
0                     NaN                  NaN                        NaN
1     Canine lost in care  Feline list in care  Canine shelter euthanasia
2                       0                    1                          0
3                       0                    0                          0
4                       0                    0                          0
...                   ...                  ...                        ...
7304                    0                    0                         22
7305                    0                    0                         17
7306                    0                    0                         12
7307                    0                    0                         21
7308                    0                    0                         16

0                           NaN                               NaN  \
0                           NaN                               NaN
1     Feline shelter euthanasia  Canine owner intended euthanasia
2                             0                                 0
3                             0                                 0
4                             0                                 0
...                         ...                               ...
7304                          0                                 0
7305                          0                                 0
7306                          2                                 0
7307                          0                                 0
7308                          2                                 0

0                                  NaN
0                                  NaN
1     Feline owner intended euthanasia
2                                    0
3                                    0
4                                    0
...                                ...
7304                                 0
7305                                 0
7306                                 0
7307                                 0
7308                                 0

[7309 rows x 35 columns]>

In [10]:
df.describe(include="all", exclude = None)

,Georgia Department of Agriculture: Shelter Report Data Export,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
count,0,7308,7308,7308,7308,7308,7308,7308,7308,7308,0,7308,7308,7308,7308,7308,7308,7308,7308,7308,7308,7308,7308,7308,7308,7308,7308,7308,7308,7308,7308,7308,7308,7308,7308
unique,0,51,51,162,173,332,283,309,243,143,0,40,41,44,43,119,67,202,175,140,49,151,186,2,2,49,61,24,34,13,14,116,116,47,44
top,NaN,2021-02-01 00:00:00,2021-02-28 00:00:00,3375,Douglas County Animal Shelter,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
freq,NaN,153,153,50,50,909,2832,1008,2663,3217,NaN,6244,6746,6564,6927,4988,5961,2995,3903,2002,5364,2078,3518,7307,7307,6627,6561,5788,5543,7061,6903,3085,3988,6219,6702

In [36]:
df3=pd.read_csv('shelter-report-data-export-august-2024_modified.csv')

# Remove null values
df3 = df3.drop(columns=['Unnamed: 10'])
#df3 = df3.dropna()

# Display the first few rows to verify the data
#print(df3.head())

# Display information about the DataFrame
#print(df3.info())
#df2=pd.read_excel('Data Request-Ganesan.xlsx')

# Assuming df is already loaded
#headers = df.iloc[0]
#df = pd.DataFrame(df.values[1:], columns=headers)

# Reset the index
df3.reset_index(drop=True, inplace=True)

# Display the DataFrame
pd.set_option('display.max_columns', None)

df3
#df3.info
#df3.describe(include="all", exclude = None)

# Merge the two DataFrames on the "Shelter Name" column
#combined_df = pd.merge(df, df2, on='Shelter Name', how='outer')

,Report Period Start,Report Period End,License Number,Shelter Name,Canine starting animal count,Feline starting animal count,Canine stray at large,Feline stray at large,Canine relinquished by owner,Feline relinquished by owner,Canine intake owner intended euthanasia,Feline intake owner intended euthanasia,Canine transferred in from agency,Feline transferred in from agency,Canine other intakes,Feline other intakes,Canine adoption,Feline adoption,Canine returned to owner,Feline returned to owner,Canine transferred to another agency,Feline transferred to another agency,Canine returned to field,Feline returned to field,Canine other live outcome,Feline other live outcome,Canine died in care,Feline died in care,Canine lost in care,Feline list in care,Canine shelter euthanasia,Feline shelter euthanasia,Canine owner intended euthanasia,Feline owner intended euthanasia
0,7/1/2020,7/31/2020,33105331,ALAPAHA ANIMAL CONTROL/SHELTER,0,0,12,3,3,0,0,0,0,0,0,0,2,0,1,0,12,2,0,0,0,0,0,0,0,1,0,0,0,0
1,8/1/2020,8/31/2020,33105331,ALAPAHA ANIMAL CONTROL/SHELTER,27,11,18,11,9,0,0,0,0,0,0,0,0,0,2,0,24,11,0,0,0,0,0,0,0,0,0,0,0,0
2,9/1/2020,9/30/2020,33105331,ALAPAHA ANIMAL CONTROL/SHELTER,2,10,2,10,0,0,0,0,0,0,0,0,0,0,0,0,2,10,0,0,0,0,0,0,0,0,0,0,0,0
3,10/1/2020,10/31/2020,33105331,ALAPAHA ANIMAL CONTROL/SHELTER,11,0,11,0,0,0,0,0,0,0,0,0,0,0,2,0,9,0,0,0,0,0,0,0,0,0,0,0,0,0
4,11/1/2020,11/30/2020,33105331,ALAPAHA ANIMAL CONTROL/SHELTER,6,13,5,13,1,0,0,0,0,0,0,0,0,0,0,0,6,13,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7302,4/1/2024,4/30/2024,3396397,WORTH COUNTY ANIMAL SHELTER,36,5,37,41,32,75,0,0,21,64,0,0,27,22,18,0,26,35,0,0,0,127,0,0,0,0,22,0,0,0
7303,5/1/2024,5/31/2024,3396397,WORTH COUNTY ANIMAL SHELTER,19,17,52,47,14,12,0,0,10,31,0,0,6,17,36,2,31,24,0,0,0,39,0,0,0,0,17,0,0,0
7304,6/1/2024,6/30/2024,3396397,WORTH COUNTY ANIMAL SHELTER,38,40,53,87,13,12,0,0,6,17,0,0,8,7,15,0,23,15,0,0,0,60,0,0,0,0,12,2,0,0
7305,7/1/2024,7/31/2024,3396397,WORTH COUNTY ANIMAL SHELTER,61,35,66,51,9,12,0,0,22,16,0,0,6,2,26,1,21,22,0,0,0,46,0,0,0,0,21,0,0,0
7306,8/1/2024,8/31/2024,3396397,WORTH COUNTY ANIMAL SHELTER,52,30,67,43,8,6,0,0,12,8,0,0,6,5,7,2,61,33,0,0,0,45,0,0,0,0,16,2,0,0

In [38]:
df2=pd.read_excel('Data Request-Ganesan.xlsx')

# Reset the index
df2.reset_index(drop=True, inplace=True)

# Display the DataFrame
pd.set_option('display.max_columns', None)

df2

,Shelter Name,EIN,Organization Type,City,State,Zip Code,County,Data Year,Total Intake Gross,Total Intake Net,Total Intake Stray At Large,Total Intake Relinquished By Owner,Total Intake Transferred In,Total Intake Other Intakes,Total Intake Owner Intended Euthanasia,Total Intake Reason Not Given,Canine Total Intake Gross,Canine Total Intake Net,Canine Intake Stray at Large,Canine Intake Relinquished By Owner,Canine Intake Transferred In,Canine Intake Other Intakes,Canine Intake Owner Intended Euthanasia,Canine Intake Reason Not Given,Feline Total Intake Gross,Feline Total Intake Net,Feline Intake Stray At Large,Feline Intake Relinquished By Owner,Feline Intake Transferred In,Feline Intake Other Intakes,Feline Intake Owner Intended Euthanasia,Feline Intake Reason Not Given,Undesignated Species Total Intake Gross,Undesignated Species Total Intake Net,Undesignated Species Intake Stray at Large,Undesignated Species Intake Relinquished by Owner,Undesignated Species Intake Transferred In,Undesignated Species Intake Other Intakes,Undesignated Species Intake Owner Intended Euthanasia,Undesignated Species Intake Reason Not Given
0,The Haven,63-1253853,Animal Shelter with a Government Contract,Fairhope,AL,36532,Baldwin County,2023,403.0,134.0,8.0,118.0,269.0,8.0,0.0,0.0,160.0,52.0,3.0,45.0,108.0,4.0,0.0,0.0,243.0,82.0,5.0,73.0,161.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,City of Fairhope Animal Control Shelter,63-6001254,Government Animal Services,Fairhope,AL,36532,Baldwin County,2023,342.0,340.0,335.0,0.0,2.0,4.0,1.0,0.0,189.0,187.0,183.0,0.0,2.0,4.0,0.0,0.0,153.0,153.0,152.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,"A New Leash on Life, Inc.",34-2013011,Shelter without a Government Contract,Brownsboro,AL,35741,Madison County,2022,2400.0,651.0,184.0,301.0,1749.0,166.0,0.0,0.0,1252.0,329.0,72.0,167.0,923.0,90.0,0.0,0.0,1148.0,322.0,112.0,134.0,826.0,76.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,City of Huntsville Animal Services,63-6001296,Government Animal Services,Huntsville,AL,35805,Madison County,2023,6036.0,6036.0,4917.0,953.0,0.0,99.0,67.0,0.0,3665.0,3665.0,2852.0,682.0,0.0,79.0,52.0,0.0,2371.0,2371.0,2065.0,271.0,0.0,20.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,God's Feral Felines,46-4565871,Shelter without a Government Contract,Arab,AL,35016,Cullman County,2023,332.0,312.0,232.0,43.0,20.0,21.0,0.0,16.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,332.0,312.0,232.0,43.0,20.0,21.0,0.0,16.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3940,Thompson Animal Control,06-6002107,Government Animal Services,Thompson,CT,6277,Windham County,"No Data from 2023, 2022, or 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3941,Colorado City/Hildale City Animal Control,86-0266404,Government Animal Services,Colorado City,AZ,86021,Mohave County,"No Data from 2023, 2022, or 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3942,Kaufman County Animal Control,75-2678512,Government Animal Services,Kaufman,TX,75142,Kaufman County,"No Data from 2023, 2022, or 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3943,Brackettville Animal Shelter,74-6000380,Government Animal Services,Brackettville,TX,78832,Kinney County,"No Data from 2023, 2022, or 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3944,Bentonville Animal Services,71-6000642,Government Animal Services,Bentonville,AR,72712,Benton County,"No Data from 2023, 2022, or 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
# Merge the two DataFrames on the "Shelter Name" column
combined_df = pd.merge(df3, df2, on='Shelter Name', how='outer')

combined_df

,Report Period Start,Report Period End,License Number,Shelter Name,Canine starting animal count,Feline starting animal count,Canine stray at large,Feline stray at large,Canine relinquished by owner,Feline relinquished by owner,Canine intake owner intended euthanasia,Feline intake owner intended euthanasia,Canine transferred in from agency,Feline transferred in from agency,Canine other intakes,Feline other intakes,Canine adoption,Feline adoption,Canine returned to owner,Feline returned to owner,Canine transferred to another agency,Feline transferred to another agency,Canine returned to field,Feline returned to field,Canine other live outcome,Feline other live outcome,Canine died in care,Feline died in care,Canine lost in care,Feline list in care,Canine shelter euthanasia,Feline shelter euthanasia,Canine owner intended euthanasia,Feline owner intended euthanasia,EIN,Organization Type,City,State,Zip Code,County,Data Year,Total Intake Gross,Total Intake Net,Total Intake Stray At Large,Total Intake Relinquished By Owner,Total Intake Transferred In,Total Intake Other Intakes,Total Intake Owner Intended Euthanasia,Total Intake Reason Not Given,Canine Total Intake Gross,Canine Total Intake Net,Canine Intake Stray at Large,Canine Intake Relinquished By Owner,Canine Intake Transferred In,Canine Intake Other Intakes,Canine Intake Owner Intended Euthanasia,Canine Intake Reason Not Given,Feline Total Intake Gross,Feline Total Intake Net,Feline Intake Stray At Large,Feline Intake Relinquished By Owner,Feline Intake Transferred In,Feline Intake Other Intakes,Feline Intake Owner Intended Euthanasia,Feline Intake Reason Not Given,Undesignated Species Total Intake Gross,Undesignated Species Total Intake Net,Undesignated Species Intake Stray at Large,Undesignated Species Intake Relinquished by Owner,Undesignated Species Intake Transferred In,Undesignated Species Intake Other Intakes,Undesignated Species Intake Owner Intended Euthanasia,Undesignated Species Intake Reason Not Given
0,7/1/2020,7/31/2020,33105331.0,ALAPAHA ANIMAL CONTROL/SHELTER,0.0,0.0,12.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,1.0,0.0,12.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8/1/2020,8/31/2020,33105331.0,ALAPAHA ANIMAL CONTROL/SHELTER,27.0,11.0,18.0,11.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,24.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,9/1/2020,9/30/2020,33105331.0,ALAPAHA ANIMAL CONTROL/SHELTER,2.0,10.0,2.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10/1/2020,10/31/2020,33105331.0,ALAPAHA ANIMAL CONTROL/SHELTER,11.0,0.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11/1/2020,11/30/2020,33105331.0,ALAPAHA ANIMAL CONTROL/SHELTER,6.0,13.0,5.0,13.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11613,NaN,NaN,NaN,Thompson Animal Control,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,06-6002107,Government Animal Services,Thompson,CT,6277.0,Windham County,"No Data from 2023, 2022, or 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11614,NaN,NaN,NaN,Colorado City/Hildale City Animal Control,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86-0266404,Government Animal Services,Colorado City,AZ,86021.0,Mohave County,"No Data from 2023, 2022, or 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11615,NaN,NaN,NaN,Kaufman County Animal Control,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75-2678512,Government Animal Services,Kaufman,TX,75142.0,Kaufman County,"No Data from 2023, 2022, or 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11616,NaN,NaN,NaN,Brackettville Animal Shelter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74-6000380,Government Animal Services,Brackettville,TX,78832.0,Kinney County,"No Data from 2023, 2022, or 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11617,NaN,NaN,NaN,Bentonville Animal Services,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71-6000642,Government Animal Services,Bentonville,AR,72712.0,Benton County,"No Data from 2023, 2022, or 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Statistical Power Analysis

In [36]:
import statsmodels.stats.power as smp

# Define parameters
effect_size = (0.2)  # Example effect size
alpha = (0.01)       # Significance level
power = 0.80       # Desired power

# Create a power analysis object
analysis = smp.TTestIndPower()

# Calculate sample size
sample_size = analysis.solve_power(effect_size=effect_size, alpha=alpha, power=power, alternative='two-sided')
print(f"Required sample size: {sample_size}")

Required sample size: 585.609280111476

In [12]:
# Assuming df is your dataframe
columns_to_convert = df.columns[4:]

for col in columns_to_convert:
    df[col] = df[col].astype(int)
    
# Reset the index
df.reset_index(drop=True, inplace=True)

df.describe()

ValueError: invalid literal for int() with base 10: 'ALAPAHA ANIMAL CONTROL/SHELTER'

# Scraping the data

In [2]:
# Importing Libraries

import requests
from bs4 import BeautifulSoup

In [ ]:
# Import statements
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import seaborn as sns
from pathlib import Path

Path('./data').mkdir(exist_ok=True)

# Helper function for extracting and persisting data
def extract_df(csv_name):
    '''
    Extracts dataframe from the data set given a CSV filename. Persists locally to avoid redudant network calls and unnecessary load on Github.

    Parameters:
        csv_name (str) - CSV filename, e.g. "blood_pressure"
    Returns:
        A pandas dataframe
    '''
    try:
        return pd.read_csv(f'./data/{csv_name}.csv')
    except:
        df = pd.read_csv(f'https://raw.githubusercontent.com/Welltory/hrv-covid19/refs/heads/master/data/{csv_name}.csv')
        df.to_csv(f'./data/{csv_name}.csv')
        return df

# Loaading the data frames
csv_names = ['blood_pressure', 'participants']
df = {}
for csv_name in csv_names:
    df[csv_name] = extract_df(csv_name)
df['blood_pressure'].head(2)

## Questions we're asking

1. What are the dimensions of the dataset (number of rows and columns)?
1. What are the data types of the variables (numerical, categorical, text, etc.)?
1. Are there any missing values, and if so, how are they represented?

In [ ]:
df['blood_pressure'].info()
print(f"Missing Values:\n{df['blood_pressure'].isnull().sum()}")

In [ ]:
df['participants'].info()
print(f"Missing Values:\n{df['participants'].isnull().sum()}")

### Interpretation
The `blood_pressure` dataframe has 721 entries of which every entry has a `user_code`, a `measurement_datetime`, a `systolic` blood pressure value, and a `diastolic` blood pressure value. There are 400+ missing values of each of the remaining columns, which we'll exclude from our analysis as we're focusing on the systolic and diastolic blood pressure data.

The `participants` dataframe has 185 entries of which every entry has a `user_code`, `gender`, `age_range`, and `weight`. There is some missing geographical information (12 missing `city` values and 6 missing `country` values) and 2 missing `height` values. There are 38 missing values for `symptoms_onset`, which could mean that either the user didn't have symptoms or failed to report symptoms.

### Transformation to add `reported_symptoms` column to participants

Here we want to add a new column dervied from `symptoms_onset` that more clearly describes whether or not the participant reported symptoms.

In [ ]:
df['participants']['reported_symptoms'] = df['participants']['symptoms_onset'].apply(lambda x: 1 if pd.notnull(x) else 0)
df['participants'].head(3)

### Transformation to add `timestamp` column to `blood_pressure`

Here we want to use the date-time strings to create a timestamp column of Pandas datetime objects.

In [5]:
df['blood_pressure']['timestamp'] = pd.to_datetime(df['blood_pressure']['measurement_datetime'])

### Adding a numeric gender column for correlation analysis

To more easily correlate our other numeric variables with gender, we're creating a `gender_index` column for which we've arbitrarily mapped `f` to 1 and `m` to 0.

In [6]:
df['participants']['gender_index'] = df['participants']['gender'].apply(lambda gender: 1 if gender == 'f' else 0)

### Joining the two datafames

We're joining the participant metadata dataframe into the blood pressure dataframe so that we can perform our analysis on a single denormalized table.

In [ ]:
df['joined'] = pd.merge(df['blood_pressure'], df['participants'], on='user_code', how='left')
df['joined'].iloc[::10].head(10)

## Questions we're asking

1. What does this blood pressure data look like visually for users that reported symptoms versus users that didn't?

In [ ]:
# Create a figure and axis
fig, ax = plt.subplots()

# Systolic blood pressure for participants who didn't report symptoms
for key, grp in df['joined'][df['joined']['reported_symptoms'] == 0].groupby(['user_code']):
    ax.plot(grp['timestamp'], grp['systolic'], label=key)

# Format the x-axis to show dates at sensible intervals
ax.xaxis.set_major_locator(mdates.DayLocator(interval=60))
ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))

# Add legend, title, and labels
ax.legend(title='User Code')
ax.set_title('Systolic Blood Pressure for Each User (no symptoms)')
ax.set_xlabel('Timestamp')
ax.set_ylabel('Systolic Blood Pressure (mmHg)')

# Rotate labels
plt.setp(ax.get_xticklabels(), rotation=45, ha='right')
plt.subplots_adjust(bottom=0.2)

# Show the plot
plt.show()

In [ ]:
# Create a figure and axis
fig, ax = plt.subplots()

# Diastolic blood pressure for participants who didn't report symptoms
for key, grp in df['joined'][df['joined']['reported_symptoms'] == 0].groupby(['user_code']):
    ax.plot(grp['timestamp'], grp['diastolic'], label=key)

# Format the x-axis to show dates at sensible intervals
ax.xaxis.set_major_locator(mdates.DayLocator(interval=60))
ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))

# Add legend, title, and labels
ax.legend(title='User Code')
ax.set_title('Diastolic Blood Pressure for Each User (no symptoms)')
ax.set_xlabel('Timestamp')
ax.set_ylabel('Diastolic Blood Pressure (mmHg)')

# Rotate labels
plt.setp(ax.get_xticklabels(), rotation=45, ha='right')
plt.subplots_adjust(bottom=0.2)

# Show the plot
plt.show()

In [ ]:
# Random sampling of user codes
sampled_user_codes = df['joined'][df['joined']['reported_symptoms'] == 1]['user_code'].drop_duplicates().sample(n=20, random_state=1)

# Create a figure and axis
fig, ax = plt.subplots()

# Systolic blood pressure for sampled participants who reported having symptoms
for key, grp in df['joined'][df['joined']['user_code'].isin(sampled_user_codes)].groupby(['user_code']):
    ax.plot(grp['timestamp'], grp['systolic'], label=key)

# Format the x-axis to show dates at sensible intervals
ax.xaxis.set_major_locator(mdates.DayLocator(interval=60))
ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))

# Add legend, title, and labels
ax.legend(title='User Code')
ax.set_title('Systolic Blood Pressure for Each User (had symptoms)')
ax.set_xlabel('Timestamp')
ax.set_ylabel('Systolic Blood Pressure (mmHg)')

# Rotate labels
plt.setp(ax.get_xticklabels(), rotation=45, ha='right')
plt.subplots_adjust(bottom=0.2)

# Show the plot
plt.show()

In [ ]:
# Create a figure and axis
fig, ax = plt.subplots()

# Diastolic blood pressure for sampled participants who reported having symptoms
for key, grp in df['joined'][df['joined']['user_code'].isin(sampled_user_codes)].groupby(['user_code']):
    ax.plot(grp['timestamp'], grp['diastolic'], label=key)

# Format the x-axis to show dates at sensible intervals
ax.xaxis.set_major_locator(mdates.DayLocator(interval=60))
ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))

# Add legend, title, and labels
ax.legend(title='User Code')
ax.set_title('Diastolic Blood Pressure for Each User (had symptoms)')
ax.set_xlabel('Timestamp')
ax.set_ylabel('Diastolic Blood Pressure (mmHg)')

# Rotate labels
plt.setp(ax.get_xticklabels(), rotation=45, ha='right')
plt.subplots_adjust(bottom=0.2)

# Show the plot
plt.show()

### Interpretation

Of the participants who did not report symptoms, only one participant consistently produced blood pressure data through usage of their wearable. The other participants show sporadic usage of their wearable.

There's a similar inconsistency for the users who did report symptoms, which indicates that for our analysis, we should hone in on the users that consistently used their wearable.

## Questions we're asking

1. What are some descriptive statistics for each of our variables?
1. What are the distributions for each of our variables? Are any of them not normal/skewed?
1. Are there any noticeable outliers?

In [ ]:
# Descriptive Statistics
print("\nDescriptive Statistics")
print("----------------------")
numeric_columns = df['joined'].select_dtypes(include=[np.number]).columns
print("Central Tendency Measures:")
print(df['joined'][numeric_columns].describe().loc[['mean', '50%']])
print("\nDispersion Measures:")
print(df['joined'][numeric_columns].describe().loc[['std', 'min', 'max']])

In [ ]:
# Check for distribution normality (skewness and kurtosis)
print("\nDistribution Measures:")
print("------------------------")
print(df['joined'][numeric_columns].skew())
print(df['joined'][numeric_columns].kurt())

In [ ]:

# Data Quality
print("\nData Quality")
print("------------")
print(f"Duplicated Rows: {df['joined'].duplicated().sum()}")
print("Checking for Inconsistent Values:")
print(df['joined'].apply(lambda x: x.value_counts().index[0]).to_frame('most_frequent_value'))


sns.boxplot(df['blood_pressure'], x='systolic')
plt.title('Systolic')
plt.xlabel('Systolic (mmHg)')
plt.show()
sns.boxplot(df['blood_pressure'], x='diastolic')
plt.title('Diastolic')
plt.xlabel('Diastolic (mmHg)')
plt.show()

### Interpretation

The boxplots above show the systolic and diastolic bloos pressures for both participants with and without reported symptoms. Systolic numbers show more variation, both above and below the mean, while diastolic shows outliers only below the mean.

The outliers will be highlighted in further analysis below (Cleanup(outliers)) to determine any relevant correlations or characterizations.

## Questions we're asking

1) How do we identify missing values?
1) How are our variables correlated?
1) How should we sample the data?
1) Does this effect change after we remove outliers, duplicates, and null values?

### Identifying Missing values

To identify missing values, we will first inspect how many datapoints were logged by each user.

In [ ]:
value_counts = df['joined']['user_code'].value_counts()
print("\nCount of datapoints for each user_code:\n", value_counts)

Of these users, only 3 logged more than 100 datapoints, with the rest of the users showing a sharp dropoff in the usage of their wearables. The user that logged the most datapoints was the one participant who did not report symptoms but showed consistent usage of their wearable from the previous set of plots. The other two users who logged more than 100 datapoints did report symptoms and can be seen in the previous plots despite the random sampling.

For our analysis, having a few more participants who didn't report symptoms would help to analyze the correlation between blood pressure and symptomatic COVID-19. Let us filter the above counts to just the users who didn't report symptoms.

In [ ]:
value_counts = df['joined'][df['joined']['reported_symptoms'] == 0]['user_code'].value_counts()
print("\nCount of datapoints for each user_code:\n", value_counts)

The above results aren't promising. The participant who didn't report symptoms that logged the second highest number of datapoints only logged 6. Also, of the 38 participants in the whole dataset who didn't report symptoms, only 8 produced blood pressure data from their wearables.

In [ ]:
threshold = 100
filtered_df = df['joined'][df['joined']['user_code'].map(df['joined']['user_code'].value_counts()) >= threshold]
unique_values_f = filtered_df['user_code'].unique()
value_counts_f = filtered_df['user_code'].value_counts()
print("\nCount of each unique value in 'unique_values_f' column:\n", value_counts_f)

There are only 3 participants who recorded more than 100 datapoints, of which 2 reported symptoms and 1 did not.

Before we proceed with sampling and cleanup, it would be interesting to see the correlation between our variables from this raw data.

In [ ]:
numeric_columns = df['joined'].select_dtypes(include=[np.number]).columns
correlation_matrix = df['joined'][numeric_columns].corr()
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=.5)
plt.title('Correlation Matrix Heatmap')
plt.show()

We can ignore the two "Unnamed" that resulted from joining the `blood_pressure` and `participants` data frames. Note that this correlation matrix was produced based on the raw timeseries data across multiple participants. 

We can see that the most correlated variables are the `functional_changes_index` with the `robinson_index`, `weight`, and the `systolic` and `diastolic` blood pressures. Height and weight are somewhat correlated with each other. Height and weight are also more correlated with diastolic blood pressure than systolic, though there's some correlation with both. 

Gender is most correlated with whether the participant reported symptoms (potential source of bias in reporting symptoms) and height, and somewhat correlated with systolic and diastolic blood pressure. 

The systolic and diastolic blood pressures are themselves correlated, and they're both correlated with the `robinson_index`. Both blood pressure readings are inversely correlated with whether the participant reported symptoms, meaning that the participants that reported symptoms tended to have lower blood pressure readings. Note that this correlation is still noticeable even though we're averaging over participants and it's evident that blood pressure is also correlated with height, weight, and gender.

### Sampling

Our initial approach for sampling will be to be stratify across our categorical variables (`gender` and `reported_symptoms`) and then perform systematic sampling across the time series.

In [ ]:
# Below code generated by ChatGPT
def systematic_sampling(df, step):
    """
    Perform systematic sampling on a dataframe by selecting every nth row.

    Parameters:
    df (pd.DataFrame): The dataframe from which to sample.
    step (int): The step size for systematic sampling, i.e., every nth row is selected.

    Returns:
    pd.DataFrame: A dataframe containing the systematically sampled rows.
    """
    return df.iloc[::step]

def stratified_systematic_sampling(df, stratify_columns, step=2):
    """
    Perform stratified systematic sampling on a dataframe, balancing the classes across categorical columns.

    The function groups the dataframe by the specified stratification columns, 
    performs systematic sampling within each group, and ensures that the classes 
    are balanced by sampling the same number of rows from each group based on the 
    smallest group size.

    Parameters:
    df (pd.DataFrame): The dataframe containing the data to be sampled.
    stratify_columns (list): List of column names to use for stratification (e.g., ['gender', 'reported_symptoms']).
    step (int): The step size for systematic sampling within each group. Defaults to 2.

    Returns:
    pd.DataFrame: A dataframe containing the balanced, systematically sampled rows across all groups.
    """
    # Group by the stratification columns
    grouped = df.groupby(stratify_columns)
    
    # Find the size of the smallest group to balance all classes
    min_group_size = grouped.size().min()
    
    # List to hold sampled dataframes
    sampled_dfs = []
    
    for _, group in grouped:
        # Perform systematic sampling
        if len(group) >= step:
            sampled_group = systematic_sampling(group, step)
        else:
            sampled_group = group
        
        # Ensure balancing by sampling only up to the size of the smallest group
        # If the group size is smaller than the min_group_size, take the whole group
        if len(sampled_group) >= min_group_size:
            sampled_dfs.append(sampled_group.sample(n=min_group_size, random_state=42))
        else:
            sampled_dfs.append(sampled_group)
    
    # Combine all the sampled dataframes
    balanced_sampled_df = pd.concat(sampled_dfs)
    
    return balanced_sampled_df

# END OF CODE GENERATED BY CHATGPT

stratify_columns = ['gender', 'reported_symptoms']
balanced_sampled_df = stratified_systematic_sampling(df['joined'], stratify_columns, step=1)
print(len(balanced_sampled_df[(balanced_sampled_df['gender'] == 'f') & (balanced_sampled_df['reported_symptoms'] == 0)]))
print(len(balanced_sampled_df[(balanced_sampled_df['gender'] == 'm') & (balanced_sampled_df['reported_symptoms'] == 0)]))
print(len(balanced_sampled_df[(balanced_sampled_df['gender'] == 'f') & (balanced_sampled_df['reported_symptoms'] == 1)]))
print(len(balanced_sampled_df[(balanced_sampled_df['gender'] == 'm') & (balanced_sampled_df['reported_symptoms'] == 1)]))

Because we're taking the size of the smallest group as the maximum number of samples per group, we're losing a lot of information due to the correlation between gender and reporting symptoms. Therefore, we need to change our approach and only sample based on `reported_symptoms`.

In [ ]:
stratify_columns = ['reported_symptoms']
balanced_sampled_df = stratified_systematic_sampling(df['joined'], stratify_columns, step=1)
print(len(balanced_sampled_df[(balanced_sampled_df['gender'] == 'f') & (balanced_sampled_df['reported_symptoms'] == 0)]))
print(len(balanced_sampled_df[(balanced_sampled_df['gender'] == 'm') & (balanced_sampled_df['reported_symptoms'] == 0)]))
print(len(balanced_sampled_df[(balanced_sampled_df['gender'] == 'f') & (balanced_sampled_df['reported_symptoms'] == 1)]))
print(len(balanced_sampled_df[(balanced_sampled_df['gender'] == 'm') & (balanced_sampled_df['reported_symptoms'] == 1)]))

This is now both balanced across our two classses as well as has a sufficient amount of data for our analysis. Let's see our correlation heatmap again.

In [ ]:
numeric_columns = balanced_sampled_df.select_dtypes(include=[np.number]).columns
correlation_matrix = balanced_sampled_df[numeric_columns].corr()
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=.5)
plt.title('Correlation Matrix Heatmap')
plt.show()

### Cleanup

#### Just the right variables
We're going to focus our analysis on a few variables of interest: `gender`/`gender_index`, `diastolic`, `reported_symptoms`, `height`, and `weight`. We're dropping the unnamed index columns from the merge operation, and we're dropping `functional_changes_index`, `circulatory_efficiency`, `kerdo_vegetation_index`, and `robinson_index` because these have low correlation with `reported_symptoms`. We're dropping `systolic` blood pressure because of its strong correlation with `diastolic` blood pressure, but we're keeping `height` and `weight` for feature engineering.

In [ ]:
cleaned_df = balanced_sampled_df[['gender', 'gender_index', 'diastolic', 'reported_symptoms', 'height', 'weight']]
cleaned_df.info()

In [ ]:
cleaned_df.describe()

#### Missing Data
As seen above in the `.info()` output, there is no missing data.

#### Duplicates

In [ ]:
cleaned_df.drop_duplicates()
cleaned_df.info()

There are no duplicates.

#### Outliers

`diastolic`, `height`, and `weight` now our only continuous variables.

In [ ]:
# Box plots to identify outliers
plt.figure(figsize=(10, 6))
sns.boxplot(data=cleaned_df, x='reported_symptoms', y='diastolic')
plt.title('Diastolic Box Plot')
plt.xlabel('Reported Symptoms')
plt.ylabel('Diastolic Blood Pressure (mmHg)')
plt.show()

In [ ]:
# Violin plot to identify correlation of outliers with reported_symptoms
plt.figure(figsize=(10, 6))
sns.violinplot(x="reported_symptoms", y="diastolic", data=cleaned_df)
plt.title('Diastolic Violin Plot')
plt.xlabel('Reported Symptoms')
plt.ylabel('Diastolic Blood Pressure (mmHg)')
plt.show()

The outliers don't appear to be true, and this is corroborated by the fact that there were few participants who did not report symptoms. Therefore, we will remove them.

In [ ]:
cleaned_df = cleaned_df[(cleaned_df['reported_symptoms'] == 1) | ((cleaned_df['reported_symptoms'] == 0) & (cleaned_df['diastolic'] >= 50))]
plt.figure(figsize=(10, 6))
sns.boxplot(data=cleaned_df, x='reported_symptoms', y='diastolic')
plt.title('Diastolic Box Plot')
plt.xlabel('Reported Symptoms')
plt.ylabel('Diastolic Blood Pressure (mmHg)')
plt.show()

In [ ]:
plt.figure(figsize=(10, 6))
sns.boxplot(data=cleaned_df, x='gender', y='height')
plt.title('Height Box Plot')
plt.xlabel('Gender')
plt.ylabel('Height (cm)')
plt.show()

In [ ]:
plt.figure(figsize=(10, 6))
sns.boxplot(data=cleaned_df, x='gender', y='weight')
plt.title('Weight Box Plot')
plt.xlabel('Gender')
plt.ylabel('Weight (kg)')
plt.show()

The height and weight outliers intuitively look to be true, so we won't remove them.

### Feature Engineering

Though we suspect `height` is only correlated with `reported_symptoms` by the gender bias and `weight` by itself has low correlation, it would be interesting to see the correlation with body mass index (BMI), which is formulated as weight in kilograms over height in meters squarerd.

In [ ]:
cleaned_df['bmi'] = cleaned_df['weight'] / np.power(cleaned_df['height'] / 100, 2)

plt.figure(figsize=(10, 6))
sns.histplot(data=cleaned_df, x='bmi')
plt.title('bmi Histogram')
plt.xlabel('BMI')
plt.ylabel('Count')
plt.show()

The distribution is skewed, so we will apply a logarithm to the column.

In [ ]:
cleaned_df['bmi'] = np.log(cleaned_df['bmi'])

plt.figure(figsize=(10, 6))
sns.histplot(data=cleaned_df, x='bmi')
plt.title('bmi Histogram')
plt.xlabel('BMI')
plt.ylabel('Count')
plt.show()

### Data Transformation

We will now normalize `diastolic`.

In [ ]:
plt.figure(figsize=(10, 6))
sns.histplot(data=cleaned_df, x='diastolic')
plt.title('diastolic Histogram')
plt.xlabel('Diastolic (mmHg)')
plt.ylabel('Count')
plt.show()

The distribution looks roughly normal, so we'll use z-score scaling.

In [ ]:
normalized_df = cleaned_df.copy()
normalized_df['diastolic'] = (normalized_df['diastolic'] - normalized_df['diastolic'].mean()) / normalized_df['diastolic'].std()

plt.figure(figsize=(10, 6))
sns.histplot(data=normalized_df, x='diastolic')
plt.title('diastolic Histogram')
plt.xlabel('Diastolic (mmHg), scaled by z-score')
plt.ylabel('Count')
plt.show()

We will now normalize `bmi`.

In [ ]:
normalized_df['bmi'] = (normalized_df['bmi'] - normalized_df['bmi'].mean()) / normalized_df['bmi'].std()

plt.figure(figsize=(10, 6))
sns.histplot(data=normalized_df, x='bmi')
plt.title('BMI Histogram')
plt.xlabel('log(BMI), scaled by z-score')
plt.ylabel('Count')
plt.show()

### Variable Relationships

Let's view our correlation heatmap again along with some pair plots.

In [ ]:
correlation_matrix = normalized_df[['gender_index', 'bmi', 'diastolic', 'reported_symptoms']].corr()
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=.5)
plt.title('Correlation Matrix Heatmap')
plt.show()

In [ ]:
sns.pairplot(normalized_df[['gender_index', 'bmi', 'diastolic', 'reported_symptoms']], hue="reported_symptoms", diag_kind="kde")
plt.suptitle('Pair Plot')
plt.tight_layout()
plt.show()

### Dimensionality Reduction

Principal Component Analysis 

Both BMI and and the Diastolic Blood Pressure are both Gaussian distributions, which lend itself to Principal Component Analysis. Please note, originally BMI was right-skewed. After log transformation, the data was slightly less skewed and more Gaussian.

In [ ]:
from sklearn.decomposition import PCA
##Select the columns for PCA
X = normalized_df[['bmi', 'diastolic']]

#Initialize PCA to reduce to 1 component (or more if needed)

pca = PCA(n_components=1)

#Fit and transform the data
X_pca = pca.fit_transform(X)

#Create a new DataFrame with the principal component(s)
df_pca = pd.DataFrame(X_pca, columns=['PCA1'])

#Optionally, you can view how much variance is explained by the components
explained_variance = pca.explained_variance_ratio_

#Output the PCA result and explained variance

print([df_pca])
print('Explained variance ratio:', explained_variance)

# Interpretation

In [ ]:
corrected_df = normalized_df.copy()
corrected_df['PCA1'] = X_pca
correlation_matrix = corrected_df[['reported_symptoms','PCA1']].corr()
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=.5)
plt.title('Correlation Matrix between Reported Symptoms and Principal Component "1" Heatmap')
plt.show()
corrected_df.head(10)

The heatmap results show that there is little, if any, correlation between the reported symptoms and the top principal component.



## Reference

[1] Pravdin, Pavel (2022). *Welltory COVID-19 and Wearables Open Data Research [dataset].* 22 July 2022. Welltory Inc. CC0-1.0 License. https://github.com/Welltory/hrv-covid19